# This is a basic workflow to help you deploy an ADF ARM template to a higher environment

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches:
      - qa
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The environment the job wil run on
    environment: QA

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout-adf
      uses: actions/checkout@v3

    - name: export-arm-template
      uses: Azure/data-factory-export-action@v1.2.0
      with:
        # Directory that contains the Data Factory resources
        # Dev Data Factory resource ID (for validating ARM template)
        id: ${{ vars.ADF_DEV_RESOURCE_ID }}

    # Upload build artifact
    - name: archive-build-artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: adf-build-QA
        # A file, directory or wildcard pattern that describes what to upload
        path: adf/armTemplate
        if-no-files-found: error
        
  # Download build artifact and deploy
  publish:
    needs: build

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # The environment the job wil run on
    environment: QA

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout-adf
      uses: actions/checkout@v3

    - name: download-build-artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Artifact name
        name: adf-build-QA
        # Destination path
        path: adf-build-QA

    - name: azure-login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        # Data Factory resource group name
        resourceGroupName: ${{ vars.ADF_RG_NAME }}
        # Data factory name
        dataFactoryName: ${{ vars.ADF_FACTORY_NAME }}
        # ARM template file name
        armTemplateFile: adf-build-QA/ARMTemplateForFactory.json
        # ARM template parameters file name
        armTemplateParametersFile: adf/ArmTemplateParametersForFactory-QA.json
        # Parameters which will be replaced in the ARM template
        #additionalParameters: # optional, default is 
        # Parameters which skip the Az module installation
        #skipAzModuleInstallation: # optional, default is false
