name: export-arm-template
on:
  push:
    branches:
      - qa

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Export ARM template
      uses: Azure/data-factory-export-action@v1.2.0
      with:
        # Directory that contains the Data Factory resources
        # Replace with your appropriate value
        id: ${{ secrets.ADF_DEV_RESOURCE_ID }}  # Store resource ID as a secret

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ExportedArmTemplate
        path: ${{github.workspace}}/exported_templates  # Change the path as needed
