
# This is a basic workflow to help you deploy an ADF ARM template to a higher environment

# For more information on GitHub Actions for Azure: https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: [ "QA" ]
    paths:
      - adf/**
  workflow_dispatch:


jobs:
  build:
    
    runs-on: ubuntu-latest
    environment: QA
    name: 'This deploys to QA'
    steps:
    - name: checkout-adf
      uses: actions/checkout@v3

    - name: export-arm-template
      uses: Azure/data-factory-export-action@v1.2.0
      with:
        # Directory that contains the Data Factory resources
        path: adf/
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}
        
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      with:
        # Artifact name
        name: adf-build-QA
        # A file, directory or wildcard pattern that describes what to upload
        path: adf/armTemplate
        if-no-files-found: error

  publish:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The environment the job wil run on
    environment: QA
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: checkout-adf
      uses: actions/checkout@v3

    - name: download-build-artifact
      uses: actions/download-artifact@v2.1.1
      with:
        # Artifact name
        name: adf-build-QA
        # Destination path
        path: adf-build-QA

    - name: azure-login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true

    - name: data-factory-deploy
      uses: Azure/data-factory-deploy-action@v1.2.0
      with:
        # Data Factory resource group name
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        # Data factory name
        dataFactoryName: ${{ vars.ADF_NAME }}
        # ARM template file name
        armTemplateFile: adf-build-QA/ARMTemplateForFactory.json
        # ARM template parameters file name
        armTemplateParametersFile: adf/ArmTemplateParametersForFactory-QA.json
        # Parameters which will be replaced in the ARM template
        #additionalParameters: # optional, default is 
        # Parameters which skip the Az module installation
        #skipAzModuleInstallation: # optional, default is false 
        
       
